---

version: "3"

services:
  app:
    build:
      context: ".."
      dockerfile: ".devcontainer/Dockerfile"
    user: "code"
    volumes:
      # workspace
      - "..:/workspace"
      # config
      - "$HOME/.config/nvim:/home/code/.config/nvim"
      - "$HOME/.config/git:/home/code/.config/git"
      - "$HOME/.ssh:/home/code/.ssh"
      - "$SSH_AUTH_SOCK:/ssh-agent"
      - "$HOME/.gnupg:/home/code/.gnupg"
      # docker
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "SSH_AUTH_SOCK=/ssh-agent"

...
